"""
Test script — fires a requirement notification email using the same code path
as the live app.

Usage:
    python test_email.py [--to your@email.com] [--category "Spices & Herbs"]

Defaults:
    --to        reads from first seller email in DB (or use --to flag)
    --category  "Spices & Herbs"
"""
import argparse
import json
import sys
from pathlib import Path

# ── Bootstrap the same config the app uses ───────────────────────────────────
BASE_DIR = Path(__file__).resolve().parent

with open(BASE_DIR / 'creds.json') as f:
    DB_CONFIG = json.load(f)

import resend
resend.api_key = DB_CONFIG.get('resendapikey', '')

import os
APP_URL = os.environ.get('APP_URL', 'https://bigspice.in')

# Pull in the helpers directly from app.py
from app import _requirement_email_html

# ── CLI args ──────────────────────────────────────────────────────────────────
parser = argparse.ArgumentParser(description='Test-fire a requirement notification email')
parser.add_argument('--to',       default=None,              help='Recipient email address')
parser.add_argument('--category', default='Spices & Herbs',  help='Category to use in the email')
parser.add_argument('--ad-id',    default=1,    type=int,    help='Ad/listing ID for the CTA link')
args = parser.parse_args()

# ── Fake requirement data ──────────────────────────────────────────────────────
AD_ID       = args.ad_id
BUYER_NAME  = 'Test Buyer'
TITLE       = f'[TEST] Looking for premium {args.category}'
DESCRIPTION = (
    'This is a test requirement generated by test_email.py. '
    'We are looking for high-quality bulk supply of the above category. '
    'Please respond with your best price and availability.'
)
CATEGORY    = args.category

# ── Resolve recipient ─────────────────────────────────────────────────────────
recipient = args.to
if not recipient:
    import psycopg2
    from psycopg2.extras import RealDictCursor
    try:
        conn = psycopg2.connect(
            host=DB_CONFIG['host'], port=DB_CONFIG['port'],
            dbname=DB_CONFIG['dbname'], user=DB_CONFIG['username'],
            password=DB_CONFIG['password']
        )
        cur = conn.cursor(cursor_factory=RealDictCursor)
        cur.execute("""
            SELECT DISTINCT u.email FROM users u
            JOIN ads a ON a.userid = u.id
            WHERE u.role = 'seller' AND u.email IS NOT NULL
              AND a.category = %s
              AND (a.listingtype IS NULL OR a.listingtype != 'requirement')
            LIMIT 1
        """, (CATEGORY,))
        row = cur.fetchone()
        cur.close(); conn.close()
        if row:
            recipient = row['email']
            print(f'[test] Auto-selected seller email from DB: {recipient}')
        else:
            print(f'[test] No seller found in DB for category "{CATEGORY}".')
            print('[test] Tip: pass --to your@email.com to override.')
            sys.exit(1)
    except Exception as e:
        print(f'[test] DB lookup failed: {e}')
        print('[test] Pass --to your@email.com to skip DB lookup.')
        sys.exit(1)

# ── Build and send ────────────────────────────────────────────────────────────
listing_url = f'{APP_URL}/listing.html?id={AD_ID}'
html = _requirement_email_html(BUYER_NAME, TITLE, DESCRIPTION, CATEGORY, listing_url)

print(f'[test] Sending to: {recipient}')
print(f'[test] Subject:    New Buyer Requirement: {TITLE}')
print(f'[test] CTA URL:    {listing_url}')

try:
    resp = resend.Emails.send({
        'from': 'BigSpice <onboarding@resend.dev>',
        'to': [recipient],
        'subject': f'New Buyer Requirement: {TITLE}',
        'html': html,
    })
    print(f'[test] ✓ Email sent! Resend response: {resp}')
except Exception as exc:
    print(f'[test] ✗ Failed to send: {exc}')
    sys.exit(1)
