// ── Canonical category list ────────────────────────────────────────────────────
export interface CategoryGroup {
  label: string;
  items: string[];
}

export const CATEGORY_GROUPS: CategoryGroup[] = [
  {
    label: "Food & Agriculture",
    items: [
      "Spices & Herbs",
      "Grains & Cereals",
      "Pulses & Legumes",
      "Nuts & Dry Fruits",
      "Oils & Fats",
      "Sugar & Sweeteners",
      "Tea & Coffee",
      "Dairy Products",
      "Fruits & Vegetables",
      "Seafood",
      "Meat & Poultry",
      "Processed & Packaged Foods",
      "Beverages",
      "Seeds & Planting Material",
      "Organic & Natural Products",
      "Agro Chemicals & Fertilizers",
    ],
  },
  {
    label: "Industrial & Supply Chain",
    items: [
      "Packaging Materials",
      "Machinery & Equipment",
      "Chemicals & Raw Materials",
      "Laboratory & Testing Equipment",
      "Safety & Protective Equipment",
      "Cold Chain & Refrigeration",
      "Industrial Tools & Hardware",
    ],
  },
  {
    label: "Professional Services",
    items: [
      "Consulting & Advisory",
      "Quality Testing & Certification",
      "Legal & Compliance",
      "Financial & Accounting",
      "Marketing & Branding",
      "Market Research & Analytics",
      "Training & Education",
    ],
  },
  {
    label: "Logistics & Supply Chain Services",
    items: [
      "Freight Forwarding",
      "Customs & Import/Export",
      "Warehousing & Storage",
      "Cold Chain Logistics",
      "Last-Mile Delivery",
      "Packaging & Labelling Services",
    ],
  },
  {
    label: "Technical Services",
    items: [
      "Machinery Installation & Repair",
      "Calibration & Testing Services",
      "IT & Software Solutions",
      "Food Processing Technology",
      "Quality Control & Inspection",
    ],
  },
  {
    label: "Other",
    items: ["Other"],
  },
];

// ── Tags per category (for buyers/sellers to narrow down listings) ─────────────
export const CATEGORY_TAGS: Record<string, string[]> = {
  "Spices & Herbs": [
    "Turmeric",
    "Black Pepper",
    "Red Chilli",
    "Cumin",
    "Coriander",
    "Cardamom",
    "Cloves",
    "Cinnamon",
    "Ginger",
    "Garlic",
    "Fenugreek",
    "Mustard Seeds",
    "Saffron",
    "Fennel",
    "Paprika",
    "Cayenne",
    "Tamarind",
    "Star Anise",
    "Nutmeg",
    "Bay Leaves",
  ],
  "Grains & Cereals": [
    "Basmati Rice",
    "Non-Basmati Rice",
    "Wheat",
    "Maize / Corn",
    "Barley",
    "Oats",
    "Millet",
    "Sorghum",
    "Ragi",
    "Jowar",
    "Bajra",
    "Buckwheat",
    "Quinoa",
    "Semolina",
    "Rice Flour",
    "Wheat Flour",
  ],
  "Pulses & Legumes": [
    "Chickpeas",
    "Lentils",
    "Kidney Beans",
    "Green Moong",
    "Yellow Moong",
    "Urad Dal",
    "Toor Dal",
    "Chana Dal",
    "Soybean",
    "Peas",
    "Masoor Dal",
    "Black Beans",
  ],
  "Nuts & Dry Fruits": [
    "Almonds",
    "Cashews",
    "Walnuts",
    "Pistachios",
    "Raisins",
    "Dates",
    "Figs",
    "Peanuts",
    "Hazelnuts",
    "Pine Nuts",
    "Macadamia",
    "Apricots",
    "Cranberries",
  ],
  "Oils & Fats": [
    "Coconut Oil",
    "Mustard Oil",
    "Groundnut Oil",
    "Sesame Oil",
    "Sunflower Oil",
    "Rice Bran Oil",
    "Palm Oil",
    "Olive Oil",
    "Ghee",
    "Butter",
    "Canola Oil",
    "Flaxseed Oil",
  ],
  "Sugar & Sweeteners": [
    "White Sugar",
    "Brown Sugar",
    "Jaggery",
    "Palm Sugar",
    "Honey",
    "Molasses",
    "Stevia",
    "Coconut Sugar",
    "Agave",
  ],
  "Tea & Coffee": [
    "Assam Tea",
    "Darjeeling Tea",
    "Green Tea",
    "Black Tea",
    "White Tea",
    "Herbal Tea",
    "Masala Chai",
    "Arabica Coffee",
    "Robusta Coffee",
    "Instant Coffee",
    "Cold Brew",
    "Oolong Tea",
  ],
  "Dairy Products": [
    "Milk Powder",
    "Cheese",
    "Butter",
    "Ghee",
    "Cream",
    "Yogurt",
    "Paneer",
    "Condensed Milk",
    "Whey Protein",
    "Casein",
  ],
  "Fruits & Vegetables": [
    "Mango",
    "Banana",
    "Grapes",
    "Pomegranate",
    "Onion",
    "Potato",
    "Tomato",
    "Garlic Bulb",
    "Ginger Root",
    "Capsicum",
    "Avocado",
    "Papaya",
    "Pineapple",
    "Lemon",
    "Okra",
    "Spinach",
  ],
  Seafood: [
    "Shrimp / Prawns",
    "Fish Fillet",
    "Salmon",
    "Tuna",
    "Crab",
    "Lobster",
    "Squid",
    "Dried Fish",
    "Fish Meal",
    "Fish Oil",
    "Oysters",
    "Tilapia",
    "Catfish",
  ],
  "Meat & Poultry": [
    "Chicken",
    "Beef",
    "Lamb / Mutton",
    "Pork",
    "Turkey",
    "Duck",
    "Frozen Meat",
    "Processed Meat",
    "Halal Meat",
    "Sausages",
    "Cold Cuts",
  ],
  "Processed & Packaged Foods": [
    "Canned Goods",
    "Snacks",
    "Instant Noodles",
    "Sauces & Condiments",
    "Pickles",
    "Jams & Preserves",
    "Bakery Products",
    "Frozen Foods",
    "Ready Meals",
    "Health Foods",
    "Baby Foods",
  ],
  Beverages: [
    "Fruit Juices",
    "Energy Drinks",
    "Soft Drinks",
    "Mineral Water",
    "Coconut Water",
    "Plant-Based Milk",
    "Beer",
    "Wine",
    "Spirits",
    "Kombucha",
  ],
  "Seeds & Planting Material": [
    "Vegetable Seeds",
    "Grain Seeds",
    "Oil Seeds",
    "Herb Seeds",
    "Hybrid Seeds",
    "Organic Seeds",
    "Flower Seeds",
    "Seedlings",
  ],
  "Organic & Natural Products": [
    "Organic Spices",
    "Organic Grains",
    "Natural Extracts",
    "Herbal Supplements",
    "Superfoods",
    "Ayurvedic Products",
    "Essential Oils",
    "Dried Herbs",
  ],
  "Agro Chemicals & Fertilizers": [
    "Pesticides",
    "Herbicides",
    "Fungicides",
    "NPK Fertilizer",
    "Organic Fertilizer",
    "Micronutrients",
    "Bio-pesticides",
    "Growth Regulators",
    "Soil Conditioners",
  ],
  "Packaging Materials": [
    "Jute Bags",
    "HDPE Bags",
    "PP Woven Bags",
    "Vacuum Pouches",
    "Corrugated Boxes",
    "PET Bottles",
    "Glass Jars",
    "Flexible Packaging",
    "Shrink Wrap",
    "Labels & Stickers",
  ],
  "Machinery & Equipment": [
    "Spice Grinding Machines",
    "Sorting & Grading Machines",
    "Drying Equipment",
    "Milling Machines",
    "Conveyor Systems",
    "Food Processing Machines",
    "Packaging Machines",
    "Cold Storage Equipment",
  ],
  "Chemicals & Raw Materials": [
    "Food Grade Chemicals",
    "Preservatives",
    "Food Additives",
    "Flavours & Fragrances",
    "Colours & Dyes",
    "Industrial Solvents",
    "Starch & Glucose",
    "Gums & Stabilizers",
  ],
  "Laboratory & Testing Equipment": [
    "Moisture Analyzers",
    "Spectrophotometers",
    "pH Meters",
    "Microscopes",
    "Centrifuges",
    "Test Kits",
    "Chromatography Equipment",
  ],
  "Safety & Protective Equipment": [
    "Gloves",
    "Face Masks",
    "Safety Goggles",
    "Protective Clothing",
    "Hairnets",
    "Steel-Toe Boots",
    "First Aid Kits",
  ],
  "Cold Chain & Refrigeration": [
    "Refrigerated Containers",
    "Cold Storage Units",
    "Blast Freezers",
    "Reefer Trucks",
    "Insulated Packaging",
    "Temperature Loggers",
  ],
  "Industrial Tools & Hardware": [
    "Weighing Scales",
    "Material Handling Equipment",
    "Pallets",
    "Industrial Shelving",
    "Forklifts",
    "Pumps & Valves",
  ],
  "Consulting & Advisory": [
    "Export Strategy",
    "Market Entry",
    "Trade Finance Advisory",
    "Supply Chain Consulting",
    "Regulatory Compliance",
    "Business Development",
  ],
  "Quality Testing & Certification": [
    "ISO Certification",
    "HACCP",
    "FSSAI",
    "Organic Certification",
    "Lab Testing",
    "Food Safety Audit",
    "Third-Party Inspection",
  ],
  "Legal & Compliance": [
    "Trade Law",
    "Contract Drafting",
    "IP & Trademarks",
    "Import/Export Licensing",
    "Regulatory Filing",
  ],
  "Financial & Accounting": [
    "Trade Finance",
    "Invoice Factoring",
    "Letters of Credit",
    "Bookkeeping",
    "Tax Advisory",
    "Audit Services",
  ],
  "Marketing & Branding": [
    "Brand Strategy",
    "Digital Marketing",
    "SEO & SEM",
    "Social Media",
    "Packaging Design",
    "Trade Show Marketing",
  ],
  "Market Research & Analytics": [
    "Commodity Price Reports",
    "Demand Forecasting",
    "Competitor Analysis",
    "Market Sizing",
    "Consumer Insights",
  ],
  "Training & Education": [
    "Food Safety Training",
    "GMP Training",
    "Export Procedures",
    "Trade Finance Workshops",
    "Spice Grading Courses",
  ],
  "Freight Forwarding": [
    "Air Freight",
    "Sea Freight (FCL)",
    "Sea Freight (LCL)",
    "Road Freight",
    "Express Courier",
    "Multimodal Logistics",
  ],
  "Customs & Import/Export": [
    "Customs Clearance",
    "HS Code Classification",
    "Import/Export Documentation",
    "Tariff Consulting",
    "Bonded Warehousing",
  ],
  "Warehousing & Storage": [
    "Dry Warehousing",
    "Bonded Warehouse",
    "Distribution Centre",
    "Pick & Pack",
    "Inventory Management",
  ],
  "Cold Chain Logistics": [
    "Temperature-Controlled Transport",
    "Refrigerated Storage",
    "Freeze-Dry Logistics",
    "Cold Chain Monitoring",
  ],
  "Last-Mile Delivery": [
    "Same-Day Delivery",
    "B2B Distribution",
    "Rural Delivery",
    "Urban Express",
    "Hyperlocal Delivery",
  ],
  "Packaging & Labelling Services": [
    "Contract Packaging",
    "Private Label",
    "Relabelling",
    "Co-packing",
    "Compliance Labelling",
  ],
  "Machinery Installation & Repair": [
    "Installation",
    "Preventive Maintenance",
    "Breakdown Repair",
    "Retrofitting",
    "Spare Parts Supply",
  ],
  "Calibration & Testing Services": [
    "Instrument Calibration",
    "Electrical Testing",
    "Pressure Testing",
    "Flow Measurement",
    "Non-Destructive Testing",
  ],
  "IT & Software Solutions": [
    "ERP for Agriculture",
    "Inventory Software",
    "Traceability Platforms",
    "E-commerce Development",
    "Digital Trade Tools",
    "Blockchain for Supply Chain",
  ],
  "Food Processing Technology": [
    "Extraction Technology",
    "Freeze Drying",
    "Spray Drying",
    "Fermentation Technology",
    "Encapsulation",
    "Irradiation",
  ],
  "Quality Control & Inspection": [
    "Pre-Shipment Inspection",
    "Loading Supervision",
    "Quality Sampling",
    "Sensory Evaluation",
    "Pesticide Residue Testing",
  ],
  Other: ["Other"],
};

/** Flat list for the scrollable category tags bar and search dropdowns */
export const ALL_CATEGORIES: string[] = CATEGORY_GROUPS.flatMap((g) => g.items);
